# Copyright (c) 2016-2017 Enproduktion GmbH & Laber's Lab e.U. (FN 394440i, Austria)

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '2'

# INFO
# We connect to Fluentd on local address because links dont work:
# https://github.com/docker/compose/issues/2657

services:

  spark-master:
    image: makeomaticio/jupyter-pyspark
    ports:
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: spark.master

  jupyter:
    image: makeomaticio/jupyter-pyspark
    ports:
      - 8888:8888
    volumes:
      - ~/.mom/jupyter:/home/jovyan/work
    command: ["start-notebook.sh", "--NotebookApp.password='sha1:8d009f30c821:4ae5eeefe2fca8c1f06b24129b8d6f4c2c72044e'"]
    # NotebookApp.password is generated using IPython.lib.passwd() (pip install IPython)
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: jupyter

  s3:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ~/.mom/s3:/export
    env_file:
      - s3.env
    # env file uses encrypted ansible vault for following vars:
    # environment:
    #   - MINIO_ACCESS_KEY=
    #   - MINIO_SECRET_KEY=
    command: [server, /export]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: s3

  spark-worker1:
    image: makeomaticio/jupyter-pyspark
    volumes:
      - ~/.mom/spark/worker1:/scratch
    environment:
      - SPARK_WORKER_DIR=/scratch
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: spark.worker01

# Submit application
# docker exec spark_spark-worker1_1 ./bin/spark-submit --master spark://spark-master:7077 examples/src/main/python/pi.py 100

networks:
  default:
    external:
      name: mom
