# Copyright (c) 2016-2017 Enproduktion GmbH & Laber's Lab e.U. (FN 394440i, Austria)

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

- name: Create jupyter directory
  file:
    path: ~/.mom/jupyter
    state: directory
    mode: 0777

- name: Create s3 directory
  file:
    path: ~/.mom/s3
    state: directory
    mode: 0777

- name: Create worker01 directory
  file:
    path: ~/.mom/spark/worker1
    state: directory
    mode: 0777

- name: Synchronize jupyter dockerstack
  synchronize:
    src: ../docker/mom-jupyter
    dest: /mom/

- name: Synchronize jupyter examples
  synchronize:
    src: ../docker/mom-jupyter/examples
    dest: ~/.mom/jupyter

- name: Start jupyter stack
  docker_service:
    project_src: /mom/mom-jupyter
    state: present

# - name: Add jupyter firewall rule
#   firewalld:
#     port: 8888/tcp
#     permanent: true
#     state: enabled
#     immediate: yes
